from __future__ import annotations

import weakref
from functools import partial
from types import (
    BuiltinMethodType,
    FunctionType,
    LambdaType,
    MethodType,
    MethodWrapperType,
)
from typing import Any, Callable, Literal, TypeVar, cast
from warnings import warn

_T = TypeVar("_T")


class WeakCallback:
    def __init__(
        self,
        obj: Any,
    ) -> None:
        mod = getattr(obj, "__module__", None) or ""
        name = getattr(obj, "__name__", None) or ""
        self._key = f"{mod}:{name}@{hex(id(obj))}"
        self._alive = True

    def __eq__(self, other: object) -> bool:
        # sourcery skip: swap-if-expression
        if not isinstance(other, WeakCallback):
            return NotImplemented
        return self._key == other._key

    def cb(self, args: tuple[Any, ...]) -> None:
        raise NotImplementedError()

    @classmethod
    def create(
        cls,
        obj: Callable,
        *args: Any,
        max_args: int | None = None,
        finalize: Callable[[WeakCallback], Any] | None = None,
        strong_ref: bool = True,
    ) -> WeakCallback:
        return weak_callable(
            obj, *args, max_args=max_args, finalize=finalize, strong_func=strong_ref
        )

    def _try_ref(
        self,
        obj: _T,
        finalize: Callable[[WeakCallback], Any] | None = None,
        on_error: Literal["raise", "warn", "ignore"] = "warn",
    ) -> Callable[[], _T | None]:
        _cb = None if finalize is None else _kill_and_finalize(self, finalize)
        try:
            return weakref.ref(obj, _cb)
        except TypeError:
            if on_error == "raise":
                raise
            if on_error == "warn":
                # FIXME: special case (move me)
                mod = getattr(obj, "__module__", None) or ""
                if "QtCore" not in mod:
                    warn(f"failed to create weakref for {obj!r}, returning strong ref")

            def _strong_ref() -> _T:
                return obj

            return _strong_ref


def _kill_and_finalize(
    wcb: WeakCallback, finalize: Callable[[WeakCallback], Any]
) -> Callable[[weakref.ReferenceType], None]:
    def _cb(_: weakref.ReferenceType) -> None:
        if wcb._alive:
            wcb._alive = False
            finalize(wcb)

    return _cb


def weak_callable(
    cb: Callable,
    *args: Any,
    max_args: int | None = None,
    finalize: Callable[[WeakCallback], Any] | None = None,
    strong_func: bool = True,
) -> WeakCallback:
    if isinstance(cb, WeakCallback):
        return cb
    if not callable(cb):
        raise TypeError(f"unsupported type {type(cb)}")

    kwargs = {}
    if isinstance(cb, partial):
        if max_args is not None:
            nargs = len(cb.args)
            if nargs:
                max_args += nargs
        args = cb.args + args
        kwargs = cb.keywords
        cb = cb.func

    cls_base = "_WeakFunction"
    if isinstance(cb, (FunctionType, LambdaType)):
        cls_base = "_StrongFunction" if strong_func else "_WeakFunction"

    elif isinstance(cb, MethodType):
        cls_base = "_WeakMethod"

    elif isinstance(cb, (MethodWrapperType, BuiltinMethodType)):
        if cb is setattr:
            obj, attr, *_ = args
            return _WeakSetattr(obj, attr, max_args=max_args, finalize=finalize)
        cls_base = "_WeakBuiltin"

    _cls_args: tuple[Any, ...] = ()
    _cls_kwargs: dict[str, Any] = {}
    if args:
        cls_base += "Args"
        _cls_args = args
    if max_args is not None:
        cls_base += "Clipped"
        _cls_kwargs["max_args"] = max_args
    if kwargs:
        cls_base += "Kwargs"
        _cls_kwargs.update(kwargs)
    if "Strong" not in cls_base:
        _cls_kwargs["finalizer"] = finalize

    Cls = cast("type[WeakCallback]", globals()[cls_base])
    return Cls(cb, *_cls_args, **_cls_kwargs)


class _WeakSetattr(WeakCallback):
    """Caller to set an attribute on an object."""

    def __init__(
        self,
        obj: object,
        attr: str,
        max_args: int | None = None,
        finalize: Callable | None = None,
    ) -> None:
        super().__init__(obj)
        self._max_args = max_args
        self._obj_ref = self._try_ref(obj, finalize)
        self._attr = attr

    def cb(self, args: tuple[Any, ...]) -> None:
        obj = self._obj_ref()
        if obj is None:
            raise ReferenceError("weakly-referenced object no longer exists")
        if self._max_args is not None:
            args = args[: self._max_args]
        setattr(obj, self._attr, args[0] if len(args) == 1 else args)

    def ref(self) -> object | None:
        return self._obj_ref()


######################################################################
# START_AUTOGENERATED_CODE


class _StrongFunction(WeakCallback):
    def __init__(self, obj: FunctionType) -> None:
        super().__init__(obj)
        self._func = obj

    def cb(self, args: tuple[Any, ...]) -> None:
        func = self._func
        func(*args)


class _StrongFunctionKwargs(WeakCallback):
    def __init__(self, obj: FunctionType, **kwargs: Any) -> None:
        super().__init__(obj)
        self._func = obj
        self._kwargs = kwargs

    def cb(self, args: tuple[Any, ...]) -> None:
        func = self._func
        func(*args, **self._kwargs)


class _StrongFunctionClipped(WeakCallback):
    def __init__(self, obj: FunctionType, max_args: int) -> None:
        super().__init__(obj)
        self._func = obj
        self._max_args = max_args

    def cb(self, args: tuple[Any, ...]) -> None:
        func = self._func
        func(*args[: self._max_args])


class _StrongFunctionClippedKwargs(WeakCallback):
    def __init__(self, obj: FunctionType, max_args: int, **kwargs: Any) -> None:
        super().__init__(obj)
        self._func = obj
        self._max_args = max_args
        self._kwargs = kwargs

    def cb(self, args: tuple[Any, ...]) -> None:
        func = self._func
        func(*args[: self._max_args], **self._kwargs)


class _StrongFunctionArgs(WeakCallback):
    def __init__(self, obj: FunctionType, *args: Any) -> None:
        super().__init__(obj)
        self._func = obj
        self._args = args

    def cb(self, args: tuple[Any, ...]) -> None:
        func = self._func
        func(*self._args, *args)


class _StrongFunctionArgsKwargs(WeakCallback):
    def __init__(self, obj: FunctionType, *args: Any, **kwargs: Any) -> None:
        super().__init__(obj)
        self._func = obj
        self._args = args
        self._kwargs = kwargs

    def cb(self, args: tuple[Any, ...]) -> None:
        func = self._func
        func(*self._args, *args, **self._kwargs)


class _StrongFunctionArgsClipped(WeakCallback):
    def __init__(self, obj: FunctionType, *args: Any, max_args: int) -> None:
        super().__init__(obj)
        self._func = obj
        self._args = args
        self._max_args = max_args

    def cb(self, args: tuple[Any, ...]) -> None:
        func = self._func
        func(*self._args, *args[: self._max_args])


class _StrongFunctionArgsClippedKwargs(WeakCallback):
    def __init__(
        self, obj: FunctionType, *args: Any, max_args: int, **kwargs: Any
    ) -> None:
        super().__init__(obj)
        self._func = obj
        self._args = args
        self._max_args = max_args
        self._kwargs = kwargs

    def cb(self, args: tuple[Any, ...]) -> None:
        func = self._func
        func(*self._args, *args[: self._max_args], **self._kwargs)


class _WeakFunction(WeakCallback):
    def __init__(
        self, obj: FunctionType, finalizer: Callable[[WeakCallback], Any] | None = None
    ) -> None:
        super().__init__(obj)
        self._ref = self._try_ref(obj, finalizer)

    def cb(self, args: tuple[Any, ...]) -> None:
        func = self._ref()
        if func is None:
            raise ReferenceError("weakly-referenced callback no longer exists")
        func(*args)


class _WeakFunctionKwargs(WeakCallback):
    def __init__(
        self,
        obj: FunctionType,
        finalizer: Callable[[WeakCallback], Any] | None = None,
        **kwargs: Any,
    ) -> None:
        super().__init__(obj)
        self._ref = self._try_ref(obj, finalizer)
        self._kwargs = kwargs

    def cb(self, args: tuple[Any, ...]) -> None:
        func = self._ref()
        if func is None:
            raise ReferenceError("weakly-referenced callback no longer exists")
        func(*args, **self._kwargs)


class _WeakFunctionClipped(WeakCallback):
    def __init__(
        self,
        obj: FunctionType,
        max_args: int,
        finalizer: Callable[[WeakCallback], Any] | None = None,
    ) -> None:
        super().__init__(obj)
        self._ref = self._try_ref(obj, finalizer)
        self._max_args = max_args

    def cb(self, args: tuple[Any, ...]) -> None:
        func = self._ref()
        if func is None:
            raise ReferenceError("weakly-referenced callback no longer exists")
        func(*args[: self._max_args])


class _WeakFunctionClippedKwargs(WeakCallback):
    def __init__(
        self,
        obj: FunctionType,
        max_args: int,
        finalizer: Callable[[WeakCallback], Any] | None = None,
        **kwargs: Any,
    ) -> None:
        super().__init__(obj)
        self._ref = self._try_ref(obj, finalizer)
        self._max_args = max_args
        self._kwargs = kwargs

    def cb(self, args: tuple[Any, ...]) -> None:
        func = self._ref()
        if func is None:
            raise ReferenceError("weakly-referenced callback no longer exists")
        func(*args[: self._max_args], **self._kwargs)


class _WeakFunctionArgs(WeakCallback):
    def __init__(
        self,
        obj: FunctionType,
        *args: Any,
        finalizer: Callable[[WeakCallback], Any] | None = None,
    ) -> None:
        super().__init__(obj)
        self._ref = self._try_ref(obj, finalizer)
        self._args = args

    def cb(self, args: tuple[Any, ...]) -> None:
        func = self._ref()
        if func is None:
            raise ReferenceError("weakly-referenced callback no longer exists")
        func(*self._args, *args)


class _WeakFunctionArgsKwargs(WeakCallback):
    def __init__(
        self,
        obj: FunctionType,
        *args: Any,
        finalizer: Callable[[WeakCallback], Any] | None = None,
        **kwargs: Any,
    ) -> None:
        super().__init__(obj)
        self._ref = self._try_ref(obj, finalizer)
        self._args = args
        self._kwargs = kwargs

    def cb(self, args: tuple[Any, ...]) -> None:
        func = self._ref()
        if func is None:
            raise ReferenceError("weakly-referenced callback no longer exists")
        func(*self._args, *args, **self._kwargs)


class _WeakFunctionArgsClipped(WeakCallback):
    def __init__(
        self,
        obj: FunctionType,
        *args: Any,
        max_args: int,
        finalizer: Callable[[WeakCallback], Any] | None = None,
    ) -> None:
        super().__init__(obj)
        self._ref = self._try_ref(obj, finalizer)
        self._args = args
        self._max_args = max_args

    def cb(self, args: tuple[Any, ...]) -> None:
        func = self._ref()
        if func is None:
            raise ReferenceError("weakly-referenced callback no longer exists")
        func(*self._args, *args[: self._max_args])


class _WeakFunctionArgsClippedKwargs(WeakCallback):
    def __init__(
        self,
        obj: FunctionType,
        *args: Any,
        max_args: int,
        finalizer: Callable[[WeakCallback], Any] | None = None,
        **kwargs: Any,
    ) -> None:
        super().__init__(obj)
        self._ref = self._try_ref(obj, finalizer)
        self._args = args
        self._max_args = max_args
        self._kwargs = kwargs

    def cb(self, args: tuple[Any, ...]) -> None:
        func = self._ref()
        if func is None:
            raise ReferenceError("weakly-referenced callback no longer exists")
        func(*self._args, *args[: self._max_args], **self._kwargs)


class _WeakMethod(WeakCallback):
    def __init__(
        self, obj: MethodType, finalizer: Callable[[WeakCallback], Any] | None = None
    ) -> None:
        super().__init__(obj)
        self._obj_ref = self._try_ref(obj.__self__, finalizer)
        self._func_ref = self._try_ref(obj.__func__, finalizer)

    def cb(self, args: tuple[Any, ...]) -> None:
        obj = self._obj_ref()
        func = self._func_ref()
        if obj is None or func is None:
            raise ReferenceError("weakly-referenced callback no longer exists")
        func(obj, *args)


class _WeakMethodKwargs(WeakCallback):
    def __init__(
        self,
        obj: MethodType,
        finalizer: Callable[[WeakCallback], Any] | None = None,
        **kwargs: Any,
    ) -> None:
        super().__init__(obj)
        self._obj_ref = self._try_ref(obj.__self__, finalizer)
        self._func_ref = self._try_ref(obj.__func__, finalizer)
        self._kwargs = kwargs

    def cb(self, args: tuple[Any, ...]) -> None:
        obj = self._obj_ref()
        func = self._func_ref()
        if obj is None or func is None:
            raise ReferenceError("weakly-referenced callback no longer exists")
        func(obj, *args, **self._kwargs)


class _WeakMethodClipped(WeakCallback):
    def __init__(
        self,
        obj: MethodType,
        max_args: int,
        finalizer: Callable[[WeakCallback], Any] | None = None,
    ) -> None:
        super().__init__(obj)
        self._obj_ref = self._try_ref(obj.__self__, finalizer)
        self._func_ref = self._try_ref(obj.__func__, finalizer)
        self._max_args = max_args

    def cb(self, args: tuple[Any, ...]) -> None:
        obj = self._obj_ref()
        func = self._func_ref()
        if obj is None or func is None:
            raise ReferenceError("weakly-referenced callback no longer exists")
        func(obj, *args[: self._max_args])


class _WeakMethodClippedKwargs(WeakCallback):
    def __init__(
        self,
        obj: MethodType,
        max_args: int,
        finalizer: Callable[[WeakCallback], Any] | None = None,
        **kwargs: Any,
    ) -> None:
        super().__init__(obj)
        self._obj_ref = self._try_ref(obj.__self__, finalizer)
        self._func_ref = self._try_ref(obj.__func__, finalizer)
        self._max_args = max_args
        self._kwargs = kwargs

    def cb(self, args: tuple[Any, ...]) -> None:
        obj = self._obj_ref()
        func = self._func_ref()
        if obj is None or func is None:
            raise ReferenceError("weakly-referenced callback no longer exists")
        func(obj, *args[: self._max_args], **self._kwargs)


class _WeakMethodArgs(WeakCallback):
    def __init__(
        self,
        obj: MethodType,
        *args: Any,
        finalizer: Callable[[WeakCallback], Any] | None = None,
    ) -> None:
        super().__init__(obj)
        self._obj_ref = self._try_ref(obj.__self__, finalizer)
        self._func_ref = self._try_ref(obj.__func__, finalizer)
        self._args = args

    def cb(self, args: tuple[Any, ...]) -> None:
        obj = self._obj_ref()
        func = self._func_ref()
        if obj is None or func is None:
            raise ReferenceError("weakly-referenced callback no longer exists")
        func(obj, *self._args, *args)


class _WeakMethodArgsKwargs(WeakCallback):
    def __init__(
        self,
        obj: MethodType,
        *args: Any,
        finalizer: Callable[[WeakCallback], Any] | None = None,
        **kwargs: Any,
    ) -> None:
        super().__init__(obj)
        self._obj_ref = self._try_ref(obj.__self__, finalizer)
        self._func_ref = self._try_ref(obj.__func__, finalizer)
        self._args = args
        self._kwargs = kwargs

    def cb(self, args: tuple[Any, ...]) -> None:
        obj = self._obj_ref()
        func = self._func_ref()
        if obj is None or func is None:
            raise ReferenceError("weakly-referenced callback no longer exists")
        func(obj, *self._args, *args, **self._kwargs)


class _WeakMethodArgsClipped(WeakCallback):
    def __init__(
        self,
        obj: MethodType,
        *args: Any,
        max_args: int,
        finalizer: Callable[[WeakCallback], Any] | None = None,
    ) -> None:
        super().__init__(obj)
        self._obj_ref = self._try_ref(obj.__self__, finalizer)
        self._func_ref = self._try_ref(obj.__func__, finalizer)
        self._args = args
        self._max_args = max_args

    def cb(self, args: tuple[Any, ...]) -> None:
        obj = self._obj_ref()
        func = self._func_ref()
        if obj is None or func is None:
            raise ReferenceError("weakly-referenced callback no longer exists")
        func(obj, *self._args, *args[: self._max_args])


class _WeakMethodArgsClippedKwargs(WeakCallback):
    def __init__(
        self,
        obj: MethodType,
        *args: Any,
        max_args: int,
        finalizer: Callable[[WeakCallback], Any] | None = None,
        **kwargs: Any,
    ) -> None:
        super().__init__(obj)
        self._obj_ref = self._try_ref(obj.__self__, finalizer)
        self._func_ref = self._try_ref(obj.__func__, finalizer)
        self._args = args
        self._max_args = max_args
        self._kwargs = kwargs

    def cb(self, args: tuple[Any, ...]) -> None:
        obj = self._obj_ref()
        func = self._func_ref()
        if obj is None or func is None:
            raise ReferenceError("weakly-referenced callback no longer exists")
        func(obj, *self._args, *args[: self._max_args], **self._kwargs)


class _WeakBuiltin(WeakCallback):
    def __init__(
        self,
        obj: MethodWrapperType | BuiltinMethodType,
        finalizer: Callable[[WeakCallback], Any] | None = None,
    ) -> None:
        super().__init__(obj)
        self._obj_ref = self._try_ref(obj.__self__, finalizer)
        self._func_name = obj.__name__

    def cb(self, args: tuple[Any, ...]) -> None:
        obj = self._obj_ref()
        func = getattr(obj, self._func_name, None)
        if func is None:
            raise ReferenceError("weakly-referenced callback no longer exists")
        func(*args)


class _WeakBuiltinKwargs(WeakCallback):
    def __init__(
        self,
        obj: MethodWrapperType | BuiltinMethodType,
        finalizer: Callable[[WeakCallback], Any] | None = None,
        **kwargs: Any,
    ) -> None:
        super().__init__(obj)
        self._obj_ref = self._try_ref(obj.__self__, finalizer)
        self._func_name = obj.__name__
        self._kwargs = kwargs

    def cb(self, args: tuple[Any, ...]) -> None:
        obj = self._obj_ref()
        func = getattr(obj, self._func_name, None)
        if func is None:
            raise ReferenceError("weakly-referenced callback no longer exists")
        func(*args, **self._kwargs)


class _WeakBuiltinClipped(WeakCallback):
    def __init__(
        self,
        obj: MethodWrapperType | BuiltinMethodType,
        max_args: int,
        finalizer: Callable[[WeakCallback], Any] | None = None,
    ) -> None:
        super().__init__(obj)
        self._obj_ref = self._try_ref(obj.__self__, finalizer)
        self._func_name = obj.__name__
        self._max_args = max_args

    def cb(self, args: tuple[Any, ...]) -> None:
        obj = self._obj_ref()
        func = getattr(obj, self._func_name, None)
        if func is None:
            raise ReferenceError("weakly-referenced callback no longer exists")
        func(*args[: self._max_args])


class _WeakBuiltinClippedKwargs(WeakCallback):
    def __init__(
        self,
        obj: MethodWrapperType | BuiltinMethodType,
        max_args: int,
        finalizer: Callable[[WeakCallback], Any] | None = None,
        **kwargs: Any,
    ) -> None:
        super().__init__(obj)
        self._obj_ref = self._try_ref(obj.__self__, finalizer)
        self._func_name = obj.__name__
        self._max_args = max_args
        self._kwargs = kwargs

    def cb(self, args: tuple[Any, ...]) -> None:
        obj = self._obj_ref()
        func = getattr(obj, self._func_name, None)
        if func is None:
            raise ReferenceError("weakly-referenced callback no longer exists")
        func(*args[: self._max_args], **self._kwargs)


class _WeakBuiltinArgs(WeakCallback):
    def __init__(
        self,
        obj: MethodWrapperType | BuiltinMethodType,
        *args: Any,
        finalizer: Callable[[WeakCallback], Any] | None = None,
    ) -> None:
        super().__init__(obj)
        self._obj_ref = self._try_ref(obj.__self__, finalizer)
        self._func_name = obj.__name__
        self._args = args

    def cb(self, args: tuple[Any, ...]) -> None:
        obj = self._obj_ref()
        func = getattr(obj, self._func_name, None)
        if func is None:
            raise ReferenceError("weakly-referenced callback no longer exists")
        func(*self._args, *args)


class _WeakBuiltinArgsKwargs(WeakCallback):
    def __init__(
        self,
        obj: MethodWrapperType | BuiltinMethodType,
        *args: Any,
        finalizer: Callable[[WeakCallback], Any] | None = None,
        **kwargs: Any,
    ) -> None:
        super().__init__(obj)
        self._obj_ref = self._try_ref(obj.__self__, finalizer)
        self._func_name = obj.__name__
        self._args = args
        self._kwargs = kwargs

    def cb(self, args: tuple[Any, ...]) -> None:
        obj = self._obj_ref()
        func = getattr(obj, self._func_name, None)
        if func is None:
            raise ReferenceError("weakly-referenced callback no longer exists")
        func(*self._args, *args, **self._kwargs)


class _WeakBuiltinArgsClipped(WeakCallback):
    def __init__(
        self,
        obj: MethodWrapperType | BuiltinMethodType,
        *args: Any,
        max_args: int,
        finalizer: Callable[[WeakCallback], Any] | None = None,
    ) -> None:
        super().__init__(obj)
        self._obj_ref = self._try_ref(obj.__self__, finalizer)
        self._func_name = obj.__name__
        self._args = args
        self._max_args = max_args

    def cb(self, args: tuple[Any, ...]) -> None:
        obj = self._obj_ref()
        func = getattr(obj, self._func_name, None)
        if func is None:
            raise ReferenceError("weakly-referenced callback no longer exists")
        func(*self._args, *args[: self._max_args])


class _WeakBuiltinArgsClippedKwargs(WeakCallback):
    def __init__(
        self,
        obj: MethodWrapperType | BuiltinMethodType,
        *args: Any,
        max_args: int,
        finalizer: Callable[[WeakCallback], Any] | None = None,
        **kwargs: Any,
    ) -> None:
        super().__init__(obj)
        self._obj_ref = self._try_ref(obj.__self__, finalizer)
        self._func_name = obj.__name__
        self._args = args
        self._max_args = max_args
        self._kwargs = kwargs

    def cb(self, args: tuple[Any, ...]) -> None:
        obj = self._obj_ref()
        func = getattr(obj, self._func_name, None)
        if func is None:
            raise ReferenceError("weakly-referenced callback no longer exists")
        func(*self._args, *args[: self._max_args], **self._kwargs)
